export default [
	{
		languageOptions: {
			ecmaVersion: 2024,
			sourceType: "module",
			globals: {
				// GNOME Shell / GJS globals
				global: "readonly",
				imports: "readonly",
				console: "readonly",
				log: "readonly",
				logError: "readonly",
				print: "readonly",
				printerr: "readonly",
				window: "readonly",

				// GObject introspection
				GObject: "readonly",
				GLib: "readonly",
				Gio: "readonly",
				Gtk: "readonly",
				Gdk: "readonly",
				Adw: "readonly",
				St: "readonly",
				Shell: "readonly",
				Meta: "readonly",
				Clutter: "readonly",
				Main: "readonly",
				ExtensionUtils: "readonly",
				Extension: "readonly",
				ExtensionPreferences: "readonly",

				// Node.js globals for potential build scripts
				process: "readonly",
				Buffer: "readonly",
				__dirname: "readonly",
				__filename: "readonly",
				require: "readonly",
				module: "readonly",
				exports: "readonly",
			},
		},
		rules: {
			// Strict error handling
			"no-console": "error",
			"no-debugger": "error",
			"no-alert": "error",

			// Variables
			"no-unused-vars": [
				"error",
				{
					argsIgnorePattern: "^_",
					varsIgnorePattern: "^_",
					caughtErrorsIgnorePattern: "^_",
				},
			],
			"no-undef": "error",
			"no-undefined": "error",
			"no-use-before-define": [
				"error",
				{ functions: false, classes: true, variables: true },
			],
			"no-redeclare": "error",
			"no-shadow": "error",
			"no-shadow-restricted-names": "error",
			"no-global-assign": "error",
			"no-implicit-globals": "error",

			// Best practices
			eqeqeq: ["error", "always"],
			"no-eval": "error",
			"no-implied-eval": "error",
			"no-new-func": "error",
			"no-with": "error",
			"no-caller": "error",
			"no-extend-native": "error",
			"no-extra-bind": "error",
			"no-floating-decimal": "error",
			"no-implicit-coercion": "error",
			"no-lone-blocks": "error",
			"no-loop-func": "error",
			"no-magic-numbers": ["error", { ignore: [-1, 0, 0.5, 1, 2] }],
			"no-multi-spaces": "error",
			"no-multi-str": "error",
			"no-new": "error",
			"no-new-wrappers": "error",
			"no-octal-escape": "error",
			"no-proto": "error",
			"no-return-assign": "error",
			"no-script-url": "error",
			"no-self-compare": "error",
			"no-sequences": "error",
			"no-throw-literal": "error",
			"no-unmodified-loop-condition": "error",
			"no-unused-expressions": "error",
			"no-useless-call": "error",
			"no-useless-concat": "error",
			"no-void": "error",
			radix: "error",
			"wrap-iife": ["error", "inside"],
			yoda: "error",

			// GNOME/GJS specific allowances
			"no-bitwise": "off", // GNOME Shell uses bitwise operations for keybindings
			"no-undefined": "off", // Common in GNOME Shell APIs
			"no-plusplus": "off", // Allow ++ and -- operators
			"no-negated-condition": "off", // Common pattern in GNOME code
			"max-params": "off", // GNOME API functions often have many parameters

			// Strict mode
			strict: ["error", "never"], // ES modules are automatically strict

			// ES6+
			"arrow-body-style": ["error", "as-needed"],
			"arrow-parens": ["error", "always"],
			"arrow-spacing": "error",
			"constructor-super": "error",
			"generator-star-spacing": "error",
			"no-class-assign": "error",
			"no-confusing-arrow": "error",
			"no-const-assign": "error",
			"no-dupe-class-members": "error",
			"no-duplicate-imports": "error",
			"no-new-symbol": "error",
			"no-restricted-imports": "error",
			"no-this-before-super": "error",
			"no-useless-computed-key": "error",
			"no-useless-constructor": "error",
			"no-useless-rename": "error",
			"no-var": "error",
			"object-shorthand": "error",
			"prefer-arrow-callback": "error",
			"prefer-const": "off", // Sometimes let is intentionally used in GNOME code
			"prefer-destructuring": ["error", { object: true, array: false }],
			"prefer-rest-params": "error",
			"prefer-spread": "error",
			"prefer-template": "error",
			"require-yield": "error",
			"rest-spread-spacing": "error",
			"symbol-description": "error",
			"template-curly-spacing": "error",
			"yield-star-spacing": "error",

			// Style (most strict)
			"array-bracket-spacing": ["error", "never"],
			"block-spacing": "error",
			"brace-style": ["error", "1tbs", { allowSingleLine: true }],
			camelcase: [
				"error",
				{
					allow: [
						// GNOME/GJS API conventions (snake_case)
						"style_class",
						"x_expand",
						"y_expand",
						"x_align",
						"y_align",
						"param_types",
						"slide_position",
						"collapse_fraction",
						"vfunc_allocate",
						"vfunc_get_preferred_width",
						"vfunc_get_preferred_height",
						"get_preferred_child_size",
						"layout_rows",
						"layout_columns",
						"n_workspaces",
						"get_active_workspace_index",
						"get_workspace_by_index",
						"active_workspace_changed",
						"focus_window",
						"get_current_time_roundtrip",
						"get_default_text_direction",
						"get_theme_node",
						"get_padding",
						"adjust_preferred_width",
						"adjust_preferred_height",
						"get_content_box",
						"get_length",
						"get_size",
						"get_origin",
						"set_origin",
						"set_size",
						"set_allocation",
						"allocate_align_fill",
						"set_child_above_sibling",
						"add_child",
						"get_child",
						"set_child",
						"remove_child",
						"get_preferred_width",
						"get_preferred_height",
						"get_monitor",
						"modifier_mask",
						"schema_id",
						"clip_to_allocation",
					],
				},
			],
			"comma-dangle": ["error", "never"],
			"comma-spacing": "error",
			"comma-style": "error",
			"computed-property-spacing": "error",
			"consistent-this": ["error", "self"],
			"eol-last": "error",
			"func-call-spacing": "error",
			"func-name-matching": "error",
			"func-style": "off", // GNOME uses both function declarations and expressions
			"id-length": [
				"error",
				{
					min: 2,
					exceptions: [
						"i",
						"j",
						"k",
						"x",
						"y",
						"z",
						"_",
						"h",
						"w",
						"g",
						"p",
						"t",
					],
				},
			],
			indent: ["error", 4, { SwitchCase: 1 }],
			"key-spacing": "error",
			"keyword-spacing": "error",
			"line-comment-position": "off", // GNOME often uses inline comments for explanation
			"lines-around-comment": "off",
			"max-depth": ["error", 4],
			"max-len": [
				"error",
				{ code: 120, ignoreComments: true, ignoreUrls: true },
			],
			"max-nested-callbacks": ["error", 3],
			"max-statements-per-line": ["error", { max: 1 }],
			"new-cap": "error",
			"new-parens": "error",
			"newline-per-chained-call": ["error", { ignoreChainWithDepth: 2 }],
			"no-array-constructor": "error",
			"no-continue": "off", // Continue statements are sometimes cleaner than complex conditionals
			"no-inline-comments": "off", // GNOME uses inline comments for clarification
			"no-lonely-if": "off", // Common pattern in GNOME code
			"no-mixed-operators": "off", // Mathematical expressions are clearer without excessive parentheses
			"no-multiple-empty-lines": ["error", { max: 2, maxEOF: 1 }],
			"no-nested-ternary": "error",
			"no-new-object": "error",
			"no-restricted-syntax": ["error", "WithStatement"],
			"no-tabs": "error",
			"no-trailing-spaces": "error",
			"no-underscore-dangle": [
				"error",
				{
					allowAfterThis: true,
					allowAfterSuper: true,
					// Allow GNOME/GJS private method and property conventions
					allow: [
						"_init",
						"_enable",
						"_disable",
						"_connect",
						"_disconnect",
						"_computeWorkspacesBoxForState",
						"_getWorkspacesBoxForState",
						"_getFirstFitAllWorkspaceBox",
						"_controls",
						"_overview",
						"_noModsTimeoutId",
						"_showWorkspaceSwitcher",
						"_workspaceOverviewMoveRight",
						"_workspaceOverviewMoveLeft",
						"_workspaceOverviewMoveUp",
						"_workspaceOverviewMoveDown",
						"_items",
						"_switcherList",
						"_scale",
						"_monitorIndex",
						"_monitor",
						"_popupTimeout",
						"_enablePopupWorkspaceHover",
						"_wm",
						"_toggle",
						"_overviewKeybindingActions",
						"_canScroll",
						"_workspaceMatrixTimeoutId",
						"_mutterSettings",
						"_keybindings",
						"_workspaceAnimation",
						"_settings",
						"_overrides",
						"_connectSettings",
						"_disconnectSettings",
						"_handleShowOverviewGridChanged",
						"_handleNumberOfWorkspacesChanged",
						"_allowedKeybindings",
						"_wsPopupList",
						"_workspaceTracker",
						"_workspaceSwitcherPopup",
						"_isWorkspacePrepended",
						"_rows",
						"_overrideProperties",
					],
				},
			],
			"no-unneeded-ternary": "error",
			"no-whitespace-before-property": "error",
			"object-curly-spacing": ["error", "never"],
			"one-var": ["error", "never"],
			"one-var-declaration-per-line": "error",
			"operator-assignment": "error",
			"operator-linebreak": ["error", "before"],
			"padded-blocks": ["error", "never"],
			"quote-props": ["error", "as-needed"],
			quotes: ["error", "single", { allowTemplateLiterals: true }],
			semi: ["error", "always"],
			"semi-spacing": "error",
			"space-before-blocks": "error",
			"space-before-function-paren": [
				"error",
				{ anonymous: "always", named: "never", asyncArrow: "always" },
			],
			"space-in-parens": "error",
			"space-infix-ops": "error",
			"space-unary-ops": "error",
			"spaced-comment": ["error", "always"],
			"unicode-bom": "error",
		},
	},
	{
		files: ["**/*.js"],
		ignores: ["node_modules/**", "dist/**", "*.min.js"],
	},
];
